# Generated by Django 2.1.7 on 2019-06-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_first_name', models.CharField(max_length=100)),
                ('your_last_name', models.CharField(max_length=100)),
                ('date_of_birth_of_child', models.DateField(blank=True, null=True)),
                ('contact_information', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['your_last_name', 'your_first_name'],
            },
        ),
    ]
