# Generated by Django 2.1.7 on 2019-04-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
