# Generated by Django 2.1.7 on 2019-04-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('waitinglist', '0005_auto_20190413_0311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Entry',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
