# Generated by Django 2.1.7 on 2019-04-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0006_auto_20190430_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='entry',
            name='birth_year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
