# Generated by Django 2.1.7 on 2019-04-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0007_auto_20190430_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='entry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
