# Generated by Django 2.1.7 on 2019-04-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0009_auto_20190430_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='contact',
            new_name='contact_information',
        ),
    ]
